import type { Metadata } from "next";
import { Inter, Roboto_Mono, Coming_Soon } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";


  const supreme = localFont({
    src: [
      {
        path: '../../public/fonts/Supreme-Bold.ttf',
        weight: '400'
      },
      {
        path: '../../public/fonts/Supreme-Bold.ttf',
        weight: '700'
      }
    ],
    variable: '--font-supreme'
  });


const inter = Inter({ subsets: ["latin"] });
const robotoMono = Roboto_Mono( {subsets:["latin"]}  );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={supreme.className}>{children}</body>
    </html>
  );
}